# -*- coding: utf-8 -*-
"""파일 입출력

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gL31vEqd5rdk7N3UfqpOSTz_TQBckKUd

---
#파일(File)

### **파일 생성**
+ 파일 객체 = open(파일 이름, 파일 열기 모드, encoding='UTF-8’)
    - 파일명이 한글일 경우는 encoding='UTF-8＇을 사용

### **파일출력함수 : write()**

### **파일입력함수**
+ readline(): 파일의 첫 번째 줄을 읽어 출력하는 경우
+ readlines(): 파일의 모든 라인을 읽어서 각각의 줄을 요소로 갖는 리스트로 리턴
+ read(): 파일의 내용 전체를 문자열로 리턴

### **파일 닫기**
+ 파일 객체.close()
"""

#구글 드라이브 마운트
from google.colab import drive
drive.mount('/content/gdrive/')

fp=open('/content/gdrive/MyDrive/Colab Notebooks/지역평균기온.txt','r',encoding='utf-8')

data=fp.read()
data

data2=fp.readlines()
data2

fp.close()

fp=open('/content/gdrive/MyDrive/Colab Notebooks/지역평균기온.txt','r',encoding='utf-8')
data=fp.readlines()
fp.close

dt={}
for line in data :
    line=line.replace('\n','')
    items=line.split(',')
    dt[items[0]]=int(items[1])

print(type(dt))
print(dt)

with open('/content/gdrive/MyDrive/Colab Notebooks/지역평균기온.txt','r',encoding='utf-8') as fp:
    data=fp.readlines()
print(data)